apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 120s }
        - setWeight: 75
        - pause: { duration: 120s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/alexavoicu/ci_cd_lab:sha256:b776afeb24ee3425a9c0617c434d3ba0d4d17396a90384bc53198142e37d9a21
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
